### ISSUE TITLE
Gordon Dry reported CC_RemoteTech.dll is not working

### ISSUE THREAD

**Issue by Lisias** [net-lisias-kspu/ContractConfigurator#1]
See here:
https://forum.kerbalspaceprogram.com/index.php?/topic/91625-142-contract-configurator-v1250-2018-04-15/&do=findComment&comment=3497266

**Comment by Lisias** [comment]
I could not reproduce the problem. Things appears to work here.

Moreover,  I recompiled everything on 1.4.1, 1.4.5 and 1.5.1 and always got exactly the same binary (in size, inclusive!).

Evidences:
* My binary [bin.zip](https://github.com/net-lisias-kspu/ContractConfigurator/files/2636505/bin.zip)
* DLLs from @PiezPiedPy, original download from DropBox [here](https://www.dropbox.com/sh/fgjw0msxwd3debd/AABwGB7trw03zdLNZlPh9KEra?dl=1). 
[CC_RemoteTech.zip](https://github.com/net-lisias-kspu/ContractConfigurator/files/2636506/CC_RemoteTech.zip)
    * It works to mention that on @PiezPiedPy's [repository](https://github.com/PiezPiedPy/ContractConfigurator/tree/FixforRT), his [only commit](https://github.com/PiezPiedPy/ContractConfigurator/commit/f71be554399fe3f88cb9e8fdc4c65427e9316ab7) is essentially [identical to mine](https://github.com/net-lisias-kspu/ContractConfigurator/commit/dcb6397e54259ab9d0bb191b8855879646930a9a) - not a surprise, it was [him who told me](https://forum.kerbalspaceprogram.com/index.php?/topic/91625-142-contract-configurator-v1250-2018-04-15/&page=176&tab=comments#comment-3440424) what to do!


The "ppp" DLLs are the ones from  @PiezPiedPy above. the "new" DLLs are the ones I recompiled, being the `CC_RemoteTech.dll` the one available from [my latest release](https://github.com/net-lisias-kspu/ContractConfigurator/releases/tag/RELEASE%2F1.25.0.2).
 
![screen shot 2018-12-01 at 23 26 48](https://user-images.githubusercontent.com/64334/49334591-a1b01e80-f5c0-11e8-8ba8-db6098bd90e6.png)

**Comment by Lisias** [comment]
Gotcha! :D 

Gordon is mixing DLLs from different sources. "My" DLLs are locked to be used agains RemoteTeck 1.8 (or above) and with ContractConfigurator 1.25 (or above).

The upstreams (and PiezPiedPy's) are not locked. So you can interchange DLLs - something that I try to prevent, as I don't intent to stomp on the Maintainer's toes.

My fork's assets are not to be used on the upstream's distributions, I don't want them having to cope with my mistakes. ;)

for History:

https://forum.kerbalspaceprogram.com/index.php?/topic/91625-142-contract-configurator-v1250-2018-04-15/&do=findComment&comment=3497286

**Comment by Gordon-Dry** [comment]
Well, I had to mix the dlls to avoid the issue mentioned in OP.

**Comment by Lisias** [comment]
Mixing things and trying exactly what you are told not to do is how you test things to the break point - sometimes, with good results. Sometimes, it backfires on you. :)

You can't have the cake and eat it too.  This is how you detect a lot of errors, I'm seeing your posts and even commits with bug fixes everywhere!

Just remember to mention when you do something "unorthodox", so we don't chase our tails on the issue! :D

**Comment by Gordon-Dry** [comment]
Just to mention that this CC issue I just recognized after the other stuff with the launch clamps etc.

I swapped the dll, launched the game to see the result and one minute later I wrote the post in the forum.

So, my mismatch has nothing to do with the other issues, they happened before.

**Comment by Lisias** [comment]
Yep. But that was what hinted me that perhaps someone else was doing the same on that issue!

It ended up that **EVERYBODY** (including me) were doing the same! :D
